Added Unit tests to workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -4,7 +4,7 @@
 # https://docs.github.com/en/actions/use-cases-and-examples/deploying/deploying-net-to-azure-app-service
 
 #name: Build and deploy ASP.Net Core app to Azure Web App - wa-github-workflows
-name: deploy
+name: deploy to staging
 
 on:
   push:
@@ -35,6 +35,9 @@ jobs:
       - name: Build with dotnet
         run: dotnet build --configuration Release
 
+      #- name: Run Unit tests
+      #  run: dotnet test ./Tests/Tests.csproj --configuration Release
+        
       - name: dotnet publish
         run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
 
@@ -43,10 +46,56 @@ jobs:
         with:
           name: .net-app
           path: ${{env.DOTNET_ROOT}}/myapp
-
-  deploy:
+        
+  # https://octopus.com/blog/githubactions-running-unit-tests
+  # https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-net
+  tests:
     runs-on: ubuntu-latest
     needs: build
+    environment:
+      name: 'Production'
+    permissions: write-all
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up .NET Core
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: '8.x'
+
+      - name: Set up dependency caching for faster builds
+        uses: actions/cache@v3
+        with:
+          path: ~/.nuget/packages
+          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-nuget-
+
+      - name: Build with dotnet
+        run: dotnet build --configuration Release
+
+      - name: Run unit tests
+        run: dotnet test ./Tests/Tests.csproj --configuration Release --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults" || true
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: always()
+        with:
+          name: DotNET Tests
+          path: "**/test-results.trx"
+          reporter: dotnet-trx
+          fail-on-error: true
+
+      - name: Upload dotnet test results
+        uses: actions/upload-artifact@v4
+        with:
+          name: dotnet-results
+          path: TestResults
+        # Use always() to always run this step to publish test results when there are test failures
+        if: ${{ always() }}
+        
+  deploy:
+    runs-on: ubuntu-latest
+    needs: tests
     environment:
       name: 'Production'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
@@ -73,4 +122,3 @@ jobs:
           app-name: 'wa-github-workflows'
           slot-name: 'Production'
           package: .
-          
